# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: iOS CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  status:
    branches: [ "main" ]

jobs:
  build:
	runs-on: macos-latest
	steps:
	  - uses: actions/checkout@v2
	  - uses: maxim-lobanov/setup-xcode@v1
		with:
		  xcode-version: '15.0.1'  # 원하는 Xcode 버전으로 수정
	  - run: swift build

  test:
	runs-on: macos-latest
	needs: build
	steps:
	  - uses: actions/checkout@v2
	  - uses: maxim-lobanov/setup-xcode@v1
		with:
		  xcode-version: '15.0.1'  # 원하는 Xcode 버전으로 수정
	  - run: swift test
