# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: iOS CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  status:
    branches: [ "main" ]

env:
  SCHEME: Domain
  TEST_DEVICE: platform=iOS Simulator, name=iPhone 15, OS=17.0

jobs:
  build:
    runs-on: macos-latest
    
    steps:
      - name: Checkout project repo
        uses: actions/checkout@v3

      - name: Build
        shell: bash
        run: xcodebuild -scheme '${{ env.SCHEME }}' -sdk iphonesimulator -destination '${{ env.TEST_DEVICE }}' build

  test: 
    runs-on: macos-latest

    steps: 
    - name: Checkout project repo
      uses: actions/checkout@v2 
      
    - name: Test
      shell: bash
      run: xcodebuild -scheme '${{ env.SCHEME }} ' -sk iphonesimulator -destination '${{ env. TEST_ DEVICE }}' test
